My batis
Paw3lUlita/DeliveryService_PU pull request #4
Opened 2023-02-08 08:51 UTC by Paw3lUlita

2023-02-22 12:27 UTC, vboltrukanis requested changes

2023-02-22 12:27 UTC, vboltrukanis commented on src/main/java/com/solvd/services/AddressService.java
> +    public Address saveAddress(Address address) {
Basically add actions should be done like this:
You create an object in java (without id, bcs you don't know which id's are already taken in db)
use service to save your object
in database an id value is assigned
you receive entity from a database with id
you update id in service object
return object with id from service method

2023-02-22 12:27 UTC, vboltrukanis commented on src/main/resources/myBatis_config.xml
> +    <properties resource="application.properties"/>
Push properties file to github with the following format:
```
db.driver=
db.url=
...
```
In this case you don't reveal any credentials, but you will show exactly where this file should be saved, which properties should be assigned.
Also driver and url are not secret, so you can add them, username and password are secret, they should not be here.
Also after you pushed basic prop file, you can add it to gitignore, so you will not worry to accidentally push updated version to github.

2023-02-22 17:35 UTC, Paw3lUlita commented on src/main/java/com/solvd/services/AddressService.java
> +    public Address saveAddress(Address address) {
Yes, but here MyBatis returns entity with generated id. I've checked it already in my IDE. I saw similar solution in  Dimitrys demo repo.

2023-03-09 10:23 UTC, vboltrukanis approved these changes
lgtm

2023-03-09 13:05 UTC, merged